# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN


    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
#        in_memory:
#            memory: ~

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                login_path: /auth/login
                csrf_provider: security.csrf.token_manager # Use form.csrf_provider instead for Symfony <2.4
                check_path: fos_user_security_check
                failure_path: /auth
            logout:
                path:   /auth/logout
                target: /

            anonymous: true
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
    access_control:
        - { path: ^/auth/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/auth/register/, role: ROLE_USER }
        - { path: ^/auth/resetting/, role: ROLE_USER }
        - { path: ^/auth/admin/, role: ROLE_ADMIN }
        - { path: ^/auth/profile/, role: ROLE_USER }
        - { path: ^/au, role: ROLE_USER }
        - { path: ^/auth, role: ROLE_USER }