article_homepage:
    path:     /
    defaults: { _controller: BlogArticleBundle:Article:index }

article_post:
    path:     /post/{id}
    defaults: { _controller: BlogArticleBundle:Article:post, id = 1 }
    requirements:
        id: \d+

article_create:
    path:     /au/create
    defaults: { _controller: BlogArticleBundle:Article:create }

article_edit:
    path:     /au/edit/{id}
    defaults: { _controller: BlogArticleBundle:Article:edit }
    requirements:
        id: \d+

article_delete:
    path:     /au/delete/{id}
    defaults: { _controller: BlogArticleBundle:Article:delete }
    requirements:
        id: \d+

article_unpublished:
    path:     /unpublished
    defaults: { _controller: BlogArticleBundle:Article:unpublished }
