article_homepage:
    path:     /
    defaults: { _controller: BlogArticleBundle:Article:index }

article_post:
    path:     /post/{id}
    defaults: { _controller: BlogArticleBundle:Article:post, id = 1 }
    requirements:
        id: \d+

article_create:
    path:     /create
    defaults: { _controller: BlogArticleBundle:Article:create }
